version: '3.7'

services:
  app:
    build: ./
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3000:3000
    env_file:
      - .env

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_DBNAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGPORT: ${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
    healthcheck:
      interval: 1s
      retries: 15
      test: pg_isready -d ${DB_DBNAME} -U ${DB_USERNAME} -p ${DB_PORT}
    volumes:
      - ./create-table.sql:/docker-entrypoint-initdb.d/create_tables.sql
